import fs from "fs";
import path from "path";

const PROJECT_ROOT = path.resolve(__dirname, "..");
const SC_OUT = path.join(
  PROJECT_ROOT,
  "supply-chain-tracker",
  "sc",
  "out",
  "SupplyChain.sol",
  "SupplyChain.json",
);
const WEB_CONFIG_DIR = path.join(
  PROJECT_ROOT,
  "supply-chain-tracker",
  "web",
  "src",
  "config",
);
const WEB_CONFIG_FILE = path.join(WEB_CONFIG_DIR, "contracts.ts");

const CONTRACT_ADDRESS = "0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519"; // update if needed
const ADMIN_ADDRESS = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";
const NETWORK = {
  chainId: 31337,
  name: "Anvil Local",
  rpcUrl: "http://localhost:8545",
};

function main() {
  if (!fs.existsSync(SC_OUT)) {
    console.error("ABI file not found at", SC_OUT);
    process.exit(1);
  }

  const abiJson = JSON.parse(fs.readFileSync(SC_OUT, "utf8"));
  const abi = abiJson.abi || abiJson;

  fs.mkdirSync(WEB_CONFIG_DIR, { recursive: true });

  const content = `// Auto-generated by scripts/generate-contract-config.ts\n// Do not edit manually unless you know what you're doing\n\nexport const CONTRACT_CONFIG = {\n  address: "${CONTRACT_ADDRESS}",\n  abi: ${JSON.stringify(abi, null, 2)},\n  adminAddress: "${ADMIN_ADDRESS}"\n};\n\nexport const NETWORK_CONFIG = ${JSON.stringify(NETWORK, null, 2)};\n`;

  fs.writeFileSync(WEB_CONFIG_FILE, content, "utf8");
  console.log("Wrote", WEB_CONFIG_FILE);
}

main();
